services:
  jenkins:
    image: jenkins:jcasc
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    env_file:
      - .env
